# Generated by Django 5.0.6 on 2024-07-09 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usermodel_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'ordering': ('email',), 'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
    ]
